#include "tests.h"

void fail(char *msg)
{
    printf("FAIL: %s\n", msg) ;
}

void test_emu()
{
    struct emuctx ctx ;
    emu_init(&ctx);
    // add si, cx
    ctx.cx.w = 0x0029 ;
    ctx.si.w = 0x04ED ;
    char opcodes[] = { 0x01, 0xce } ;
    emu_write_bytes(&ctx, opcodes, 2) ;
    emu_step(&ctx) ;
    if (get_af(&ctx) == NO) fail("add si, cx - AF Flag") ;
    if (get_of(&ctx) == YES) fail("add si, cx - OF Flag") ;
    if (get_sf(&ctx) == YES) fail("add si, cx - SF Flag") ;
    if (get_cf(&ctx) == YES) fail("add si, cx - CF Flag") ;
    if (get_zf(&ctx) == YES) fail("add si, cx - CF Flag") ;
    if (ctx.si.w != 0x516) fail("add si, cx - wrong si result") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    ctx.ax.w = 0x4064 ;
    char opcodes2[] = { 0x05, 0xf, 0xf} ;
    emu_write_bytes(&ctx, opcodes2, 3) ;
    emu_step(&ctx) ;
    if (get_pf(&ctx) != YES) fail("add ax, imm16 - PF flag") ;
    if (get_af(&ctx) == NO) fail("add ax, imm16 - AF flag") ;
    if (get_of(&ctx) == YES) fail("add ax, imm16 - OF flag") ;
    if (get_sf(&ctx) == YES) fail("add ax, imm16 - SF flag") ;
    if (get_cf(&ctx) == YES) fail("add ax, imm16 - CF flag") ;
    if (get_zf(&ctx) == YES) fail("add ax, imm16 - ZF flag") ;
    if (ctx.ax.w != 0x4F73) fail("add ax, imm16 - wrong ax result") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    ctx.ax.w = 0x0060 ;
    ctx.ds.w = 0x4000 ;
    ctx.bx.w = 0x009A ;
    char opcodes3[] = { 0x09, 0x07 } ;
    emu_write_bytes(&ctx, opcodes3, 2) ;
    word value ;
    value.w =  0x012c ;
    write_mem_word(&ctx, (ctx.ds.w << 4) + ctx.bx.w, value) ;
    emu_step(&ctx) ;
    word result = read_mem_word(&ctx, (ctx.ds.w << 4) + ctx.bx.w) ;
    if (result.w != 0x016C) fail("or [bx], ax - wrong result") ;
    if (get_pf(&ctx) == YES) fail("or [bx], ax - PF flag") ;
    if (get_of(&ctx) == YES) fail("or [bx], ax - OF flag") ;
    if (get_sf(&ctx) == YES) fail("or [bx], ax - SF flag") ;
    if (get_cf(&ctx) == YES) fail("or [bx], ax - CF flag") ;
    if (get_zf(&ctx) == YES) fail("or [bx], ax - ZF flag") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    ctx.ax.w = 0x0609 ;
    char opcodes4[] = { 0x0d, 0x30, 0x30 } ;
    emu_write_bytes(&ctx, opcodes4, 3) ;
    emu_step(&ctx) ;
    if (ctx.ax.w != 0x3639) fail("or ax, 0x3030 - wrong result") ;
    if (get_pf(&ctx) == YES) fail("or ax, 0x3030 - PF flag") ;
    if (get_of(&ctx) == YES) fail("or ax, 0x3030 - OF flag") ;
    if (get_sf(&ctx) == YES) fail("or ax, 0x3030 - SF flag") ;
    if (get_cf(&ctx) == YES) fail("or ax, 0x3030 - CF flag") ;
    if (get_zf(&ctx) == YES) fail("or ax, 0x3030 - ZF flag") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    ctx.ax.w = 0x0211 ;
    ctx.bx.w = 0x0084 ;
    ctx.ds.w = 0x1C00 ;
    set_cf(&ctx, YES) ;
    char opcodes5[] = { 0x13, 0x07 } ;
    value.w = 0x00A4 ;
    write_mem_word(&ctx, (ctx.ds.w << 4) + ctx.bx.w, value) ;
    emu_write_bytes(&ctx, opcodes5, 2) ;
    emu_step(&ctx) ;
    if (ctx.ax.w != 0x02B6) fail("adc ax, [bx] - wrong result") ;
    if (get_pf(&ctx) == NO) fail("adc ax, [bx] - PF flag") ;
    if (get_af(&ctx) == YES) fail("adc ax, [bx] - AF flag") ;
    if (get_of(&ctx) == YES) fail("adc ax, [bx] - OF flag") ;
    if (get_sf(&ctx) == YES) fail("adc ax, [bx] - SF flag") ;
    if (get_cf(&ctx) == YES) fail("adc ax, [bx] - CF flag") ;
    if (get_zf(&ctx) == YES) fail("adc ax, [bx] - ZF flag") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    ctx.ax.w = 0x4F3D ;
    set_cf(&ctx, YES) ;
    char opcodes6[] = { 0x15, 0x81, 0xfd } ; // add ax, 0xfd81
    emu_write_bytes(&ctx, opcodes6, 3) ;
    emu_step(&ctx) ;
    if (ctx.ax.w != 0x4CBF) fail("adc ax, 0xfd81 - wrong result") ;
    if (get_cf(&ctx) == NO) fail("adc ax, 0xfd81 - CF flag") ;
    if (get_of(&ctx) == YES) fail("adc ax, 0xfd81 - OF flag") ;
    if (get_zf(&ctx) == YES) fail("adc ax, 0xfd81 - ZF flag") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    ctx.dx.b.l = 0x03 ;
    ctx.bx.b.l =  0x64 ;
    set_cf(&ctx, YES) ;
    char opcodes7[] = { 0x18, 0xd3 } ; // sbb bl, dl
    emu_write_bytes(&ctx, opcodes7, 2) ;
    emu_step(&ctx) ;
    if (ctx.bx.b.l != 0x60) fail("sbb bl, dl - wrong result") ;
    if (get_pf(&ctx) == YES) fail("sbb bl, dl - PF flag") ;
    if (get_af(&ctx) == YES) fail("sbb bl, dl - AF flag") ;
    if (get_of(&ctx) == YES) fail("sbb bl, dl - OF flag") ;
    if (get_sf(&ctx) == YES) fail("sbb bl, dl - SF flag") ;
    if (get_cf(&ctx) != NO) fail("sbb bl, dl - CF flag") ;
    if (get_zf(&ctx) == YES) fail("sbb bl, dl - ZF flag") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    ctx.ax.w = 0x6B3A ;
    set_cf(&ctx, YES) ;
    char opcodes8[] = { 0x1d, 0x2c, 0x4d} ; // sbb ax, 0x4D2C
    emu_write_bytes(&ctx, opcodes8, 3) ;
    emu_step(&ctx) ;
    if (ctx.ax.w != 0x1E0D) fail("sbb ax, 0x4D2C - wrong result") ;
    if (get_pf(&ctx) == NO) fail("sbb ax, 0x4D2C - PF flag") ;
    if (get_af(&ctx) != YES) fail("sbb ax, 0x4D2C - AF flag") ;
    if (get_of(&ctx) == YES) fail("sbb ax, 0x4D2C - OF flag") ;
    if (get_sf(&ctx) == YES) fail("sbb ax, 0x4D2C - SF flag") ;
    if (get_cf(&ctx) == YES) fail("sbb ax, 0x4D2C - CF flag") ;
    if (get_zf(&ctx) == YES) fail("sbb ax, 0x4D2C - ZF flag") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    ctx.dx.b.l = 0x06 ;
    ctx.ds.w = 0xb000 ;
    ctx.bx.w = 0x0010 ;
    ctx.si.w = 0x0006 ;
    char opcodes9[] = {0x22, 0x10} ;
    emu_write_bytes(&ctx, opcodes9, 2) ;
    write_mem_byte(&ctx, 0xB0016, 0xF1) ;
    emu_step(&ctx) ;
    if (ctx.dx.b.l != 0x00) fail("and bl, [bx+si]") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    ctx.ax.b.l = 0xC3 ;
    char opcodes10[] = {0x24, 0x7f} ;
    emu_write_bytes(&ctx, opcodes10, 2) ;
    emu_step(&ctx) ;
    if (ctx.ax.b.l != 0x43) fail("and al, 0x7F - wronng result") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    ctx.bx.b.l = 0x68 ;
    ctx.ax.b.l = 0x28 ;
    char opcodes11[] = {0x00, 0xd8, 0x27} ;
    emu_write_bytes(&ctx, opcodes11, 3) ;
    emu_step(&ctx) ;
    emu_step(&ctx) ;
    if (ctx.ax.b.l != 0x96) fail("daa - wronng result") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    ctx.dx.b.h = 0x41 ;
    ctx.ss.w = 0x0 ;
    ctx.bp.w = 0xE4 ;
    write_mem_byte(&ctx, 0xE8, 0x5A) ;
    char opcodes12[] = {0x2a, 0x76, 0x04} ;
    emu_write_bytes(&ctx, opcodes12, 3) ;
    emu_step(&ctx) ;
    if (ctx.dx.b.h != 0xe7) fail("sub dh, [bp+4] - wronng result") ;
    if (get_pf(&ctx) == YES) fail("sub dh, [bp+4] - PF flag") ;
    if (get_af(&ctx) == NO) fail("sub dh, [bp+4] - AF flag") ;
    if (get_sf(&ctx) != YES) fail("sub dh, [bp+4] - SF flag") ;
    if (get_cf(&ctx) != YES) fail("sub dh, [bp+4] - CF flag") ;
    if (get_zf(&ctx) != NO) fail("sub dh, [bp+4] - ZF flag") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    ctx.ax.b.l = 0x61 ;
    char opcodes13[] = {0x2c, 0x65} ;
    emu_write_bytes(&ctx, opcodes13, 2) ;
    emu_step(&ctx) ;
    if (ctx.ax.b.l != 0xFC) fail("sub al, 0x65 - wronng result") ;
    if (get_cf(&ctx) != YES) fail("sub al, 0x65 - CF flag") ;
    if (get_sf(&ctx) != YES) fail("sub al, 0x65 - SF flag") ;
    if (get_af(&ctx) != YES) fail("sub al, 0x65 - AF flag") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    ctx.ax.b.l = 0x86 ;
    ctx.ax.b.h = 0x07 ;
    char opcodes14[] = {0x28, 0xe0, 0x2f} ;
    emu_write_bytes(&ctx, opcodes14, 3) ;
    emu_step(&ctx) ;
    if (ctx.ax.b.l != 0x7F) fail("sub al, ah - wronng result") ;
    emu_step(&ctx) ;
    if (ctx.ax.b.l != 0x79) fail("das - wronng result") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    ctx.ax.w = 0x07B7 ;
    ctx.ds.w = 0x9080 ;
    ctx.si.w = 0x040E ;
    value.w = 0xA6F0 ;
    write_mem_word(&ctx, 0x90C0E, value) ;
    char opcodes15[] = {0x33, 0x04} ;
    emu_write_bytes(&ctx, opcodes15, 2) ;
    emu_step(&ctx) ;
    if (ctx.ax.w != 0xA147) fail("xor ax, [si] - wrong result") ;
    if (get_sf(&ctx) != YES) fail("xor ax, [si] - SF flag") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    ctx.ax.w = 0xB31C ;
    char opcodes16[] = {0x35, 0x22, 0x55} ;
    emu_write_bytes(&ctx, opcodes16, 3) ;
    emu_step(&ctx) ;
    if (ctx.ax.w != 0xE63E) fail("xor ax, 0x5522 - wrong result") ; 
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    ctx.ax.w = 0x0535 ;
    ctx.bx.b.l = 0x39 ;
    char opcodes17[] = {0x00, 0xd8, 0x37} ;
    emu_write_bytes(&ctx, opcodes17, 3) ;
    emu_step(&ctx) ;
    emu_step(&ctx) ;
    if (ctx.ax.w != 0x0604) fail("aaa - wrong result") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    ctx.dx.b.h = 0x05 ;
    ctx.cx.b.l = 0x06 ;
    char opcodes18[] = {0x38, 0xf1} ;
    emu_write_bytes(&ctx, opcodes18, 2) ;
    emu_step(&ctx) ;
    if (ctx.dx.b.h != 0x05) fail("cmp cl, dh - wrong result") ;
    if (ctx.cx.b.l != 0x06) fail("cmp cl, dh - wrong result") ;
    if (get_pf(&ctx) != YES) fail("cmp cl, dh - PF flag") ;
    if (get_af(&ctx) != NO) fail("cmp cl, dh - AF flag") ;
    if (get_cf(&ctx) != NO) fail("cmp cl, dh - CF flag") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    ctx.ax.b.l = 0x20 ;
    char opcodes19[] = {0x3c, 0x0d} ;
    emu_write_bytes(&ctx, opcodes19, 2) ;
    emu_step(&ctx) ;
    if (ctx.ax.b.l != 0x20) fail("cmp al, 0x0d - wrong result") ;
    if (get_cf(&ctx) != NO) fail("cmp al, 0x0d - CF flag") ;
    if (get_af(&ctx) != YES) fail("cmp al, 0x0d - AF flag") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    ctx.ax.w = 0x0438 ;
    char opcodes20[] = {0x2c, 0x35, 0x3f} ;
    emu_write_bytes(&ctx, opcodes20, 3) ;
    emu_step(&ctx) ;
    emu_step(&ctx) ;
    if (ctx.ax.w != 0x0403) fail("aas - wrong result") ;
    if (get_cf(&ctx) != NO) fail("sub al, 0x35 - CF flag") ;
    if (get_af(&ctx) != NO) fail("sub al, 0x35 - AF flag") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    ctx.ax.w = 0xFFFF ;
    char opcodes21[] = {0x50,0x5b} ;
    emu_write_bytes(&ctx, opcodes21, 2) ;
    emu_step(&ctx) ;
    emu_step(&ctx) ;
    if (ctx.bx.w != 0xFFFF) fail("pop bx - wrong result") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    ctx.ax.w = 0x00FF ;
    ctx.bx.w = 0xFF00 ;
    char opcodes22[] = {0x50,0x53, 0x58, 0x5b} ;
    emu_write_bytes(&ctx, opcodes22, 4) ;
    emu_step(&ctx) ;
    emu_step(&ctx) ;
    emu_step(&ctx) ;
    emu_step(&ctx) ;
    if (ctx.ax.w != 0xFF00) fail("pop ax - wrong result") ;
    if (ctx.bx.w != 0x00FF) fail("pop bx - wrong result") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    char opcodes23[] = {0x70,0xfe} ;
    set_of(&ctx, YES) ;
    emu_write_bytes(&ctx, opcodes23, 2) ;
    emu_step(&ctx) ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    /*
     push ax
     jo label
     pop ax
     pop dx
     pop cx
     label:
     pop bx
    */
    char opcodes24[] = {0x50, 0x70, 0x03, 0x58, 0x5a, 0x59, 0x5b} ;
    set_of(&ctx, YES) ;
    ctx.ax.w = 0xF0F0 ;
    emu_write_bytes(&ctx, opcodes24, 7) ;
    emu_step(&ctx) ;
    emu_step(&ctx) ;
    emu_step(&ctx) ;
    if (ctx.bx.w != 0xF0F0) fail("pop bx - wrong result") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    char opcodes25[] = {0x80, 0xc1, 0xff} ; // add cl, 0xff
    emu_write_bytes(&ctx, opcodes25, 3) ;
    ctx.cx.b.l = 0x01 ;
    emu_step(&ctx) ;
    if (ctx.cx.b.l != 0) fail("add cl, 0xff - wrong result") ;
    if (get_cf(&ctx) != YES) fail("add cl, 0xff - CF flag") ;
    if (get_af(&ctx) != YES) fail("add cl, 0xff - AF flag") ;
    if (get_zf(&ctx) != YES) fail("add cl, 0xff - ZF flag") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    char opcodes26[] = {0x80, 0xc9, 0xff} ;
    emu_write_bytes(&ctx, opcodes26, 3) ;
    ctx.cx.b.l = 0xff ;
    emu_step(&ctx) ;
    if (ctx.cx.b.l != 0xff) fail("or cl, 0xff - wrong result") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    char opcodes27[] = {0x80, 0xd1, 0xff} ; // adc cl, 0xff
    emu_write_bytes(&ctx, opcodes27, 3) ;
    set_cf(&ctx, YES) ;
    ctx.cx.b.l = 0x00 ;
    emu_step(&ctx) ;
    if (ctx.cx.b.l != 0x0) fail("adc cl, 0xff - wrong result") ;
    if (get_cf(&ctx) != YES) fail("adc cl, 0xff - CF flag") ;
    if (get_af(&ctx) != YES) fail("adc cl, 0xff - AF flag") ;
    if (get_of(&ctx) != NO) fail("adc cl, 0xff - OF flag") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    char opcodes28[] = {0x80, 0xd9, 0xff} ; // sbb cl, 0xff
    emu_write_bytes(&ctx, opcodes28, 3) ;
    set_cf(&ctx, YES) ;
    ctx.cx.b.l = 0x00 ;
    emu_step(&ctx) ;
    if (ctx.cx.b.l != 0x0) fail("sbb cl, 0xff - wrong result") ;
    if (get_cf(&ctx) != YES) fail("sbb cl, 0xff - CF flag") ;
    if (get_af(&ctx) != YES) fail("sbb cl, 0xff - AF flag") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    ctx.cx.w = 0x00 ;
    char opcodes29[] = {0x80, 0xd9, 0xff} ; // sbb cl, 0xff
    emu_write_bytes(&ctx, opcodes29, 3) ;
    emu_step(&ctx) ;
    if (ctx.cx.b.l != 0x01) fail("sbb cl, 0xff - wrong result") ;
    if (get_cf(&ctx) != YES) fail("sbb cl, 0xff - CF flag") ;
    if (get_af(&ctx) != YES) fail("sbb cl, 0xff - AF flag") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    char opcodes30[] = {0x80, 0xe9, 0xff} ;
    emu_write_bytes(&ctx, opcodes30, 3) ;
    ctx.cx.w = 0x00 ;
    emu_step(&ctx) ;
    if (ctx.cx.b.l != 0x01) fail("sub cl, 0xff - wrong result") ;
    if (get_cf(&ctx) != YES) fail("sub cl, 0xff - CF flag") ;
    if (get_af(&ctx) != YES) fail("sub cl, 0xff - AF flag") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    char opcodes31[] = { 0x81, 0xC2, 0xF0, 0xF0} ; // add dx,0xf0f0
    emu_write_bytes(&ctx, opcodes31, 4) ;
    ctx.dx.w = 0x4652 ;
    emu_step(&ctx) ;
    if (ctx.dx.w != 0x3742) fail("add dx,0xf0f0 - wrong result") ;
    if (get_pf(&ctx) != NO) fail("add dx,0xf0f0 - PF Flag") ;
    if (get_zf(&ctx) != NO) fail("add dx,0xf0f0 - ZF Flag") ;
    if (get_af(&ctx) != NO) fail("add dx,0xf0f0 - AF Flag") ;
    if (get_cf(&ctx) != YES) fail("add dx,0xf0f0 - CF Flag") ;
    if (get_sf(&ctx) != NO) fail("add dx,0xf0f0 - SF Flag") ;
    if (get_of(&ctx) != NO) fail("add dx,0xf0f0 - OF Flag") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    char opcodes32[] = { 0x81, 0x09, 0x05, 0x08} ; // or word [bx+di],0x805
    ctx.ds.w = 0x3800 ;
    ctx.bx.w = 0x0200 ;
    ctx.di.w = 0x0136 ;
    value.w = 0x06B3;
    write_mem_word(&ctx, 0x38336, value) ;
    emu_write_bytes(&ctx, opcodes32, 4) ;
    emu_step(&ctx) ;
    result = read_mem_word(&ctx, 0x38336) ;
    if (result.w != 0x0EB7) fail("or word [bx+di],0x805 - wrong result") ;
    if (get_pf(&ctx) != NO) fail("or word [bx+di],0x805 - PF flag") ;
    if (get_cf(&ctx) != NO) fail("or word [bx+di],0x805 - CF flag") ;
    if (get_sf(&ctx) != NO) fail("or word [bx+di],0x805 - SF flag") ;
    if (get_of(&ctx) != NO) fail("or word [bx+di],0x805 - OF flag") ;
    if (get_zf(&ctx) != NO) fail("or word [bx+di],0x805 - ZF flag") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    char opcodes33[] = { 0x81, 0x14, 0x31, 0x2D} ; // adc word [si],0x2d31
    emu_write_bytes(&ctx, opcodes33, 4) ;
    ctx.ds.w = 0xE400 ;
    ctx.si.w = 0x0040 ;
    value.w = 0x6B90;
    set_cf(&ctx, NO) ;
    write_mem_word(&ctx, 0xE4040, value) ;
    emu_step(&ctx) ;
    result = read_mem_word(&ctx, 0xE4040) ;
    if (result.w != 0x98C1) fail("adc word [si],0x2d31 - wrong result") ;
    if (get_pf(&ctx) != YES) fail("adc word [si],0x2d31 - PF flag") ;
    if (get_cf(&ctx) != NO) fail("adc word [si],0x2d31 - CF flag") ;
    if (get_sf(&ctx) != YES) fail("adc word [si],0x2d31 - SF flag") ;
    if (get_of(&ctx) != YES) fail("adc word [si],0x2d31 - OF flag") ;
    if (get_zf(&ctx) != NO) fail("adc word [si],0x2d31 - ZF flag") ;
    if (get_af(&ctx) != NO) fail("adc word [si],0x2d31 - AF flag") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    char opcodes34[] = { 0x81, 0x27, 0x52, 0x00} ; // and word [bx],0x52
    emu_write_bytes(&ctx, opcodes34, 4) ;
    ctx.ds.w = 0x0 ;
    ctx.bx.w = 0x0104 ;
    value.w = 0x47 ;
    write_mem_word(&ctx, 0x00104, value) ;
    emu_step(&ctx) ;
    result = read_mem_word(&ctx, 0x00104) ;
    if (result.w != 0x42) fail("and word [bx],0x52 - wrong result") ;
    if (get_of(&ctx) != NO) fail("and word [bx],0x52 - OF flag") ;
    if (get_cf(&ctx) != NO) fail("and word [bx],0x52 - CF flag") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    char opcodes35[] = { 0x81, 0x6c, 0x14, 0x36, 0x01} ; // sub word [si+0x14],0x136
    emu_write_bytes(&ctx, opcodes35, 5) ;
    ctx.ds.w = 0x3000 ;
    ctx.si.w = 0x0040 ;
    value.w = 0x4336 ;
    write_mem_word(&ctx, 0x30054, value) ;
    emu_step(&ctx) ;
    result = read_mem_word(&ctx, 0x30054) ;
    if (result.w != 0x4200) fail("sub word [si+0x14],0x136 - wrong result") ;
    if (get_pf(&ctx) != NO) fail("sub word [si+0x14],0x136 - PF flag") ;
    if (get_af(&ctx) == YES) fail("sub word [si+0x14],0x136 - AF flag") ;
    if (get_of(&ctx) != NO) fail("sub word [si+0x14],0x136 - OF flag") ;
    if (get_sf(&ctx) != NO) fail("sub word [si+0x14],0x136 - SF flag") ;
    if (get_cf(&ctx) != NO) fail("sub word [si+0x14],0x136 - CF flag") ;
    if (get_zf(&ctx) != NO) fail("sub word [si+0x14],0x136 - ZF flag") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    char opcodes36[] = { 0x81, 0x31, 0x05, 0x08} ; // xor word [bx+di],0x805
    emu_write_bytes(&ctx, opcodes36, 4) ;
    ctx.ds.w = 0x3800 ;
    ctx.bx.w = 0x0200 ;
    ctx.di.w = 0x0136 ;
    value.w = 0x06B3 ;
    write_mem_word(&ctx, 0x38336, value) ;
    emu_step(&ctx) ;
    result = read_mem_word(&ctx, 0x38336) ;
    if (result.w != 0x0EB6) fail("xor word [bx+di],0x805 - wrong result") ;
    if (get_pf(&ctx) != YES) fail("xor word [bx+di],0x805 - PF flag") ;
    if (get_cf(&ctx) != NO) fail("xor word [bx+di],0x805 - CF flag") ;
    if (get_of(&ctx) != NO) fail("xor word [bx+di],0x805 - OF flag") ;
    if (get_zf(&ctx) != NO) fail("xor word [bx+di],0x805 - ZF flag") ;
    if (get_sf(&ctx) != NO) fail("xor word [bx+di],0x805 - SF flag") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    char opcodes37[] = { 0x81, 0xfe, 0x00, 0x02} ; // cmp si,0x200
    emu_write_bytes(&ctx, opcodes37, 4) ;
    ctx.si.w = 0x01BA ;
    emu_step(&ctx) ;
    if (get_pf(&ctx) != YES) fail("cmp si,0x200 - PF flag") ;
    if (get_af(&ctx) == YES) fail("cmp si,0x200 - AF flag") ;
    if (get_of(&ctx) != NO) fail("cmp si,0x200 - OF flag") ;
    if (get_sf(&ctx) != YES) fail("cmp si,0x200 - SF flag") ;
    if (get_cf(&ctx) != YES) fail("cmp si,0x200 - CF flag") ;
    if (get_zf(&ctx) != NO) fail("cmp si,0x200 - ZF flag") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    char opcodes38[] = { 0x83, 0xc3, 0xff} ; // add bx, byte -0x01
    emu_write_bytes(&ctx, opcodes38, 3) ;
    ctx.bx.w = 0xFFFF ;
    emu_step(&ctx) ;
    if (ctx.bx.w != 0xFFFE) fail("add bx, byte -0x01 - wrong result") ;
    if (get_cf(&ctx) != YES) fail("add bx, byte -0x01 - CF flag") ;
    if (get_af(&ctx) != YES) fail("add bx, byte -0x01 - AF flag") ;
    if (get_zf(&ctx) != NO) fail("add bx, byte -0x01 - ZF flag") ;
    if (get_sf(&ctx) != YES) fail("add bx, byte -0x01 - SF flag") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    char opcodes39[] = { 0x83, 0x07, 0xff} ; // add word [bx], byte -0x01
    emu_write_bytes(&ctx, opcodes39, 3) ;
    ctx.ds.w = 0x072A ;
    ctx.bx.w = 0xFFFE ;
    value.w = 0xFFFF ;
    write_mem_word(&ctx, (ctx.ds.w << 4) + ctx.bx.w, value) ;
    emu_step(&ctx) ;
    result = read_mem_word(&ctx, (ctx.ds.w << 4) + ctx.bx.w ) ;
    if (result.w != 0xFFFE) fail("add word [bx], byte -0x01 - wrong result") ;
    if (get_cf(&ctx) != YES) fail("add word [bx], byte -0x01 - CF flag") ;
    if (get_af(&ctx) != YES) fail("add word [bx], byte -0x01 - AF flag") ;
    if (get_zf(&ctx) != NO) fail("add word [bx], byte -0x01 - ZF flag") ;
    if (get_sf(&ctx) != YES) fail("add word [bx], byte -0x01 - SF flag") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    char opcodes40[] = { 0x83, 0xd0, 0xff} ; // adc ax, byte -0x01
    ctx.ax.w = 0x0 ;
    emu_write_bytes(&ctx, opcodes40, 3) ;
    emu_step(&ctx) ;
    if (ctx.ax.w != 0xFFFF) fail("adc ax, byte -0x01 - wrong result") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    char opcodes41[] = { 0x83, 0x10, 0x01} ; // adc word [bx+si], byte 0x1
    emu_write_bytes(&ctx, opcodes41, 3) ;
    ctx.bx.w = 0x100 ;
    ctx.si.w = 0x100 ;
    ctx.ds.w = 0x072A ;
    value.w = 0x0 ;
    write_mem_word(&ctx, (ctx.ds.w << 4) + ctx.bx.w + ctx.si.w, value) ;
    emu_step(&ctx) ;
    result = read_mem_word(&ctx, (ctx.ds.w << 4) + ctx.bx.w + ctx.si.w) ;
    if (result.w != 0x1) fail("adc word [bx+si], byte 0x1 - wrong result") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    ctx.ax.w = 0xf9 ;
    set_cf(&ctx, YES);
    char opcodes42[] = { 0x83, 0xD8, 0xFF} ; // sbb ax,byte -0x1
    emu_write_bytes(&ctx, opcodes42, 3) ;
    emu_step(&ctx) ;
    if (ctx.ax.w != 0x00F9) fail("sbb ax,byte -0x1 - wrong result") ;
    if (get_cf(&ctx) != YES) fail("sbb ax,byte -0x1 - CF Flag") ;
    if (get_af(&ctx) != YES) fail("sbb ax,byte -0x1 - AF Flag") ;
    if (get_of(&ctx) != NO) fail("sbb ax,byte -0x1 - OF Flag") ;
    if (get_sf(&ctx) != NO) fail("sbb ax,byte -0x1 - SF Flag") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    char opcodes43[] = { 0x83, 0x5E, 0x00, 0xFE} ; // sbb word [bp+0x0],byte -0x02
    emu_write_bytes(&ctx, opcodes43, 4) ;
    set_cf(&ctx, YES);
    value.w = 0x0 ;
    ctx.ss.w = 0x0700 ;
    ctx.bp.w = 0x01 ;
    write_mem_word(&ctx, (ctx.ss.w << 4) + ctx.bp.w, value) ;
    emu_step(&ctx) ;
    result = read_mem_word(&ctx, (ctx.ss.w << 4) + ctx.bp.w ) ;
    if (result.w != 0x01) fail("sbb word [bp+0x0],byte -0x02 - wrong result") ;
    if (get_cf(&ctx) != YES) fail("sbb word [bp+0x0],byte -0x02 - CF Flag") ;
    if (get_af(&ctx) != YES) fail("sbb word [bp+0x0],byte -0x02 - AF Flag") ;
    if (get_of(&ctx) != NO) fail("sbb word [bp+0x0],byte -0x02 - OF Flag") ;
    if (get_sf(&ctx) != NO) fail("sbb word [bp+0x0],byte -0x02 - SF Flag") ;
    if (get_pf(&ctx) != YES) fail("sbb word [bp+0x0],byte -0x02 - PF Flag") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    ctx.dx.w = 0x0000 ;
    //set_af(&ctx, NO) ;
    //set_cf(&ctx, NO) ;
    char opcodes44[] = { 0x83, 0xEA, 0x01} ; // sub dx,byte +0x1
    emu_write_bytes(&ctx, opcodes44, 3) ;
    emu_step(&ctx) ;
    if (ctx.dx.w != 0xFFFF) fail("sub dx,byte +0x1 - wrong result") ;
    if (get_cf(&ctx) != YES) fail("sub dx,byte +0x1 - CF Flag") ;
    if (get_af(&ctx) != YES) fail("sub dx,byte +0x1 - AF Flag") ;
    if (get_of(&ctx) != NO) fail("sub dx,byte +0x1 - OF Flag") ;
    if (get_sf(&ctx) != YES) fail("sub dx,byte +0x1 - SF Flag") ;
    if (get_pf(&ctx) != NO) fail("sub dx,byte +0x1 - PF Flag") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    ctx.si.w = 0x10 ;
    ctx.ds.w = 0x072A ;
    char opcodes45[] = { 0x83, 0x6c, 0x10, 0x10} ; //  sub word [si+0x10],byte +0x10
    emu_write_bytes(&ctx, opcodes45, 4) ;
    value.w = 0x0 ;
    write_mem_word(&ctx, (ctx.ds.w << 4) + ctx.si.w + 0x10 , value) ;
    emu_step(&ctx) ;
    result = read_mem_word(&ctx, (ctx.ds.w << 4) + ctx.si.w + 0x10 ) ;
    if (result.w != 0xFFF0) fail("sub word [si+0x10],byte +0x10 - wrong result") ;
    if (get_cf(&ctx) != YES) fail("sub word [si+0x10],byte +0x10 - CF Flag") ;
    if (get_pf(&ctx) != NO) fail("sub word [si+0x10],byte +0x10 - PF Flag") ;
    if (get_af(&ctx) == YES) fail("sub word [si+0x10],byte +0x10 - AF Flag") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    ctx.ax.w = 0x0 ;
    char opcodes46[] = { 0x83, 0xF8, 0xFF} ; //  cmp ax,byte -0x1
    emu_write_bytes(&ctx, opcodes46, 3) ;
    emu_step(&ctx) ;
    if (ctx.ax.w != 0) fail("cmp ax,byte -0x1 - wrong result") ;
    if (get_cf(&ctx) != YES) fail("cmp ax,byte -0x1 - CF Flag") ;
    if (get_pf(&ctx) != YES) fail("cmp ax,byte -0x1 - PF Flag") ;
    if (get_af(&ctx) != YES) fail("cmp ax,byte -0x1 - AF Flag") ;
    if (get_of(&ctx) != NO) fail("cmp ax,byte -0x1 - OF Flag") ;
    if (get_zf(&ctx) != NO) fail("cmp ax,byte -0x1 - ZF Flag") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    ctx.ds.w = 0x072A ;
    ctx.bx.w = 0x0 ;
    ctx.si.w = 0x01BA ;
    char opcodes47[] = { 0x83, 0xB8, 0xFF, 0x00, 0xF0} ; //   cmp word [bx+si+0xff],byte -0x10
    emu_write_bytes(&ctx, opcodes47, 5) ;
    value.w = 0x0 ;
    write_mem_word(&ctx, (ctx.ds.w << 4) + ctx.si.w + 0xff, value) ;
    emu_step(&ctx) ;
    if (get_cf(&ctx) != YES) fail("cmp word [bx+si+0xff],byte -0x10 - CF Flag") ;
    if (get_pf(&ctx) != YES) fail("cmp word [bx+si+0xff],byte -0x10 - PF Flag") ;
    if (get_af(&ctx) != NO) fail("cmp word [bx+si+0xff],byte -0x10 - AF Flag") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    char opcodes48[] = { 0x84, 0xF0} ; // test al,dh
    emu_write_bytes(&ctx, opcodes48, 2) ;
    ctx.ax.b.l = 0x40 ;
    ctx.dx.b.h = 0xAF ;
    emu_step(&ctx) ;
    if (get_pf(&ctx) != NO) fail("test al,dh - PF Flag") ;
    if (get_of(&ctx) != NO) fail("test al,dh - OF Flag") ;
    if (get_cf(&ctx) != NO) fail("test al,dh - CF Flag") ;
    if (get_sf(&ctx) != NO) fail("test al,dh - SF Flag") ;
    if (get_zf(&ctx) != YES) fail("test al,dh - ZF Flag") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    char opcodes49[] = { 0x84, 0xA6, 0x00, 0x01} ; // test [bp+0x100],ah
    emu_write_bytes(&ctx, opcodes49, 4) ;
    ctx.ss.w = 0x800 ;
    ctx.bp.w = 0x100 ;
    value.w = 0xF9 ;
    ctx.ax.b.h = 0xff ;
    write_mem_word(&ctx, (ctx.ss.w << 4) + ctx.bp.w + 0x100, value) ;
    emu_step(&ctx) ;
    if (get_pf(&ctx) != NO) fail("test [bp+0x100],ah - PF Flag") ;
    if (get_of(&ctx) != NO) fail("test [bp+0x100],ah - OF Flag") ;
    if (get_cf(&ctx) != NO) fail("test [bp+0x100],ah- CF Flag") ;
    if (get_sf(&ctx) != YES) fail("test [bp+0x100],ah- SF Flag") ;
    if (get_zf(&ctx) != NO) fail("test [bp+0x100],ah - ZF Flag") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    char opcodes50[] = { 0x85, 0xC2} ; // test dx,ax
    emu_write_bytes(&ctx, opcodes50, 2) ;
    ctx.ax.w = 0xf900 ;
    ctx.dx.w = 0x00f9 ;
    emu_step(&ctx) ;
    if (get_cf(&ctx) != NO) fail("test dx,ax - CF Flag") ;
    if (get_pf(&ctx) != NO) fail("test dx,ax - PF Flag") ;
    if (get_zf(&ctx) != YES) fail("test dx,ax - ZF Flag") ;
    if (get_sf(&ctx) != NO) fail("test dx,ax - SF Flag") ;
    if (get_of(&ctx) != NO) fail("test dx,ax - OF Flag") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    char opcodes51[] = { 0x85, 0x84, 0xff, 0x7F} ; // test [si+0x7fff],ax
    emu_write_bytes(&ctx, opcodes51, 4) ;
    ctx.ds.w = 0x700 ;
    ctx.si.w = 0x0 ;
    ctx.ax.w = 0x00f9 ;
    value.w = 0xf900 ;
    write_mem_word(&ctx, (ctx.ds.w << 4) + ctx.si.w + 0x7fff, value) ;
    emu_step(&ctx) ;
    if (get_cf(&ctx) != NO) fail("test dx,ax - CF Flag") ;
    if (get_pf(&ctx) != NO) fail("test dx,ax - PF Flag") ;
    if (get_zf(&ctx) != YES) fail("test dx,ax - ZF Flag") ;
    if (get_sf(&ctx) != NO) fail("test dx,ax - SF Flag") ;
    if (get_of(&ctx) != NO) fail("test dx,ax - OF Flag") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    char opcodes52[] = { 0x86, 0xc3} ; // xchg al,bl
    emu_write_bytes(&ctx, opcodes52, 2) ;
    ctx.ax.b.l = 0xff ;
    ctx.bx.b.l = 0xf9 ;
    emu_step(&ctx) ;
    if (ctx.ax.b.l != 0xf9) fail("xchg al,bl - wrong result") ;
    if (ctx.bx.b.l != 0xff) fail("xchg al,bl - wrong result") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    char opcodes53[] = { 0x86, 0xA0, 0x00, 0x01} ; // xchg ah,[bx+si+0x64]
    emu_write_bytes(&ctx, opcodes53, 4) ;
    ctx.ds.w = 0x700 ;
    ctx.si.w = 0x100 ;
    ctx.bx.w = 0x100 ;
    write_mem_byte(&ctx, (ctx.ds.w << 4) + ctx.bx.w + ctx.si.w + 0x100, 0xf9) ;
    ctx.ax.b.h = 0x78 ;
    emu_step(&ctx) ;
    if (ctx.ax.b.h != 0xf9) fail("xchg ah,[bx+si+0x64] - wrong result") ;
    if (read_mem_byte(&ctx, (ctx.ds.w << 4) + ctx.bx.w + ctx.si.w + 0x100) != 0x78) fail("xchg ah,[bx+si+0x64] - wrong result") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    ctx.bx.w = 0xF0FF ;
    ctx.ax.w = 0xFFF9 ;
    value.w = 0xF9FF ;
    write_mem_word(&ctx, (ctx.ds.w << 4) + ctx.bx.w, value) ;
    char opcodes54[] = { 0x33, 0x07} ; // xor ax, [bx]
    emu_write_bytes(&ctx, opcodes54, 2) ;
    emu_step(&ctx) ;
    if (ctx.ax.w != 0x0606) fail("xor ax, [bx] - wrong result") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    char opcodes55[] = { 0x87, 0xD3} ; //  xchg dx,bx
    emu_write_bytes(&ctx, opcodes55, 2) ;
    ctx.dx.w = 0xf800 ;
    ctx.bx.w = 0x9999 ;
    emu_step(&ctx) ;
    if (ctx.dx.w != 0x9999) fail("xchg dx,bx - wrong result") ;
    if (ctx.bx.w != 0xf800) fail("xchg dx,bx - wrong result") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    char opcodes56[] = { 0x87, 0x04} ; //  xchg ax,[si]
    emu_write_bytes(&ctx, opcodes56, 2) ;
    value.w = 0xffff ;
    write_mem_word(&ctx, (ctx.ds.w << 4) + ctx.si.w, value) ;
    ctx.ax.w = 0x0f0f ;
    emu_step(&ctx) ;
    value = read_mem_word(&ctx, (ctx.ds.w << 4) + ctx.si.w);
    if (value.w != 0x0f0f) fail("xchg ax,[si] - wrong result") ;
    if (ctx.ax.w != 0xffff) fail("xchg ax,[si] - wrong result") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    char opcodes57[] = { 0x88, 0xC4} ; //  mov ah,al
    emu_write_bytes(&ctx, opcodes57, 2) ;
    ctx.ax.b.l = 0xf9 ;
    emu_step(&ctx) ;
    if (ctx.ax.b.h != 0xf9) fail("mov ah,al - wrong result");
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    char opcodes58[] = { 0x88, 0xA4, 0x00, 0xff} ; //  mov [si+0xff00],ah
    emu_write_bytes(&ctx, opcodes58, 4) ;
    ctx.ds.w = 0x700 ;
    ctx.si.w = 0x100 ;
    ctx.ax.b.h = 0xff ;
    emu_step(&ctx) ;
    value.w = read_mem_byte(&ctx, (ctx.ds.w << 4) + ctx.si.w + 0xff00) ;
    if (value.w != 0xff) fail("mov [si+0xff00],ah - wrong result");
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    char opcodes59[] = { 0x89, 0xCA} ; // mov dx,cx
    emu_write_bytes(&ctx, opcodes59, 2) ;
    ctx.cx.w = 0xf900 ;
    emu_step(&ctx) ;
    if (ctx.dx.w != 0xf900) fail("mov dx,cx - wrong result") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    char opcodes60[] = { 0x89, 0x08} ; // mov [bx+si],cx
    emu_write_bytes(&ctx, opcodes60, 2) ;
    ctx.bx.w = 0x100 ;
    ctx.si.w = 0x100 ;
    ctx.cx.w = 0xf8f7 ;
    emu_step(&ctx) ;
    value = read_mem_word(&ctx, (ctx.ds.w << 4) + ctx.bx.w + ctx.si.w) ;
    if (value.w != 0xf8f7) fail("mov [bx+si],cx - wrong result") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    char opcodes61[] = { 0x8A, 0x20} ; // mov ah,[bx+si]
    emu_write_bytes(&ctx, opcodes61, 2) ;
    ctx.bx.w = 0x100 ;
    ctx.si.w = 0x100 ;
    write_mem_byte(&ctx, (ctx.ds.w << 4) + ctx.bx.w + ctx.si.w, 0xf1) ;
    emu_step(&ctx) ;
    if (ctx.ax.b.h != 0xf1) fail("mov ah,[bx+si]") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    char opcodes62[] = { 0x8B, 0x00} ; // mov ax,[bx+si]
    emu_write_bytes(&ctx, opcodes62, 2) ;
    ctx.bx.w = 0x100 ;
    ctx.si.w = 0x100 ;
    value.w = 0xffff ;
    write_mem_word(&ctx, (ctx.ds.w << 4) + ctx.bx.w + ctx.si.w, value) ;
    emu_step(&ctx) ;
    if (ctx.ax.w != 0xffff) fail("mov ax,[bx+si]") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    char opcodes63[] = { 0x8C, 0xD8} ; // mov ax,ds
    emu_write_bytes(&ctx, opcodes63, 2) ;
    ctx.ds.w = 0xffff ;
    emu_step(&ctx) ;
    if (ctx.ax.w != 0xffff) fail("mov ax,ds") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    char opcodes64[] = { 0x8C, 0x00} ; // mov [bx+si],es
    emu_write_bytes(&ctx, opcodes64, 2) ;
    ctx.bx.w = 0x100 ;
    ctx.si.w = 0x100 ;
    ctx.es.w = 0xff00 ;
    emu_step(&ctx) ;
    value = read_mem_word(&ctx, (ctx.ds.w << 4) + ctx.bx.w + ctx.si.w) ;
    if (value.w != 0xff00) fail("mov [bx+si],es") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    char opcodes65[] = { 0x8D, 0x07} ; // lea ax,[bx]
    emu_write_bytes(&ctx, opcodes65, 2) ;
    ctx.bx.w = 0x100 ;
    ctx.ds.w = 0xfff ;
    ctx.ss.w = 0xff ; 
    emu_step(&ctx) ;
    if (ctx.ax.w != 0x100) fail("lea ax,[bx] - wrong result") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    char opcodes66[] = { 0x8E, 0xD8} ; // mov ds,ax
    emu_write_bytes(&ctx, opcodes66, 2) ;
    ctx.ax.w = 0xffff ;
    emu_step(&ctx) ;
    if (ctx.ds.w != 0xffff) fail("mov ds,ax - wrong result");
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    char opcodes67[] = { 0x8E, 0x07} ; // mov es,[bx]
    emu_write_bytes(&ctx, opcodes67, 2) ;
    value.w = 0xffff ;
    ctx.bx.w = 0x100 ;
    write_mem_word(&ctx, (ctx.ds.w << 4) + ctx.bx.w, value) ;
    emu_step(&ctx) ;
    if (ctx.es.w != 0xffff) fail("mov es,[bx] - wrong result");
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    char opcodes68[] = { 0x50, 0x8f, 0x07} ; // push ax, pop word [bx]
    emu_write_bytes(&ctx, opcodes68, 3) ;
    ctx.sp.w = 0xfffe ;
    ctx.bx.w = 0x100 ;
    ctx.ax.w = 0xf0f0 ;
    emu_step(&ctx) ;
    emu_step(&ctx) ;
    value = read_mem_word(&ctx, (ctx.ds.w << 4) + ctx.bx.w) ;
    if (value.w != 0xf0f0) fail("push ax, pop word [bx] - wrong result") ;
    emu_cleanup(&ctx) ;
    
}
