#include "tests.h"

void fail(char *msg)
{
    printf("FAIL: %s\n", msg) ;
}

void test_emu()
{
    struct emuctx ctx ;
    emu_init(&ctx);
    // add si, cx
    ctx.cx.w = 0x0029 ;
    ctx.si.w = 0x04ED ;
    char opcodes[] = { 0x01, 0xce } ;
    emu_write_bytes(&ctx, opcodes, 2) ;
    emu_step(&ctx) ;
    if (get_af(&ctx) == NO) fail("add si, cx - AF Flag") ;
    if (get_of(&ctx) == YES) fail("add si, cx - OF Flag") ;
    if (get_sf(&ctx) == YES) fail("add si, cx - SF Flag") ;
    if (get_cf(&ctx) == YES) fail("add si, cx - CF Flag") ;
    if (get_zf(&ctx) == YES) fail("add si, cx - CF Flag") ;
    if (ctx.si.w != 0x516) fail("add si, cx - wrong si result") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    ctx.ax.w = 0x4064 ;
    char opcodes2[] = { 0x05, 0xf, 0xf} ;
    emu_write_bytes(&ctx, opcodes2, 3) ;
    emu_step(&ctx) ;
    if (get_pf(&ctx) == YES) fail("add ax, imm16 - PF flag") ;
    if (get_af(&ctx) == NO) fail("add ax, imm16 - AF flag") ;
    if (get_of(&ctx) == YES) fail("add ax, imm16 - OF flag") ;
    if (get_sf(&ctx) == YES) fail("add ax, imm16 - SF flag") ;
    if (get_cf(&ctx) == YES) fail("add ax, imm16 - CF flag") ;
    if (get_zf(&ctx) == YES) fail("add ax, imm16 - ZF flag") ;
    if (ctx.ax.w != 0x4F73) fail("add ax, imm16 - wrong ax result") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    ctx.ax.w = 0x0060 ;
    ctx.ds.w = 0x4000 ;
    ctx.bx.w = 0x009A ;
    char opcodes3[] = { 0x09, 0x07 } ;
    emu_write_bytes(&ctx, opcodes3, 2) ;
    word value ;
    value.w =  0x012c ;
    write_mem_word(&ctx, (ctx.ds.w << 4) + ctx.bx.w, value) ;
    emu_step(&ctx) ;
    word result = read_mem_word(&ctx, (ctx.ds.w << 4) + ctx.bx.w) ;
    if (result.w != 0x016C) fail("or [bx], ax - wrong result") ;
    if (get_pf(&ctx) == NO) fail("or [bx], ax - PF flag") ;
    if (get_of(&ctx) == YES) fail("or [bx], ax - OF flag") ;
    if (get_sf(&ctx) == YES) fail("or [bx], ax - SF flag") ;
    if (get_cf(&ctx) == YES) fail("or [bx], ax - CF flag") ;
    if (get_zf(&ctx) == YES) fail("or [bx], ax - ZF flag") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    ctx.ax.w = 0x0609 ;
    char opcodes4[] = { 0x0d, 0x30, 0x30 } ;
    emu_write_bytes(&ctx, opcodes4, 3) ;
    emu_step(&ctx) ;
    if (ctx.ax.w != 0x3639) fail("or ax, 0x3030 - wrong result") ;
    if (get_pf(&ctx) == NO) fail("or ax, 0x3030 - PF flag") ;
    if (get_of(&ctx) == YES) fail("or ax, 0x3030 - OF flag") ;
    if (get_sf(&ctx) == YES) fail("or ax, 0x3030 - SF flag") ;
    if (get_cf(&ctx) == YES) fail("or ax, 0x3030 - CF flag") ;
    if (get_zf(&ctx) == YES) fail("or ax, 0x3030 - ZF flag") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    ctx.ax.w = 0x0211 ;
    ctx.bx.w = 0x0084 ;
    ctx.ds.w = 0x1C00 ;
    set_cf(&ctx, YES) ;
    char opcodes5[] = { 0x13, 0x07 } ;
    value.w = 0x00A4 ;
    write_mem_word(&ctx, (ctx.ds.w << 4) + ctx.bx.w, value) ;
    emu_write_bytes(&ctx, opcodes5, 2) ;
    emu_step(&ctx) ;
    if (ctx.ax.w != 0x02B6) fail("adc ax, [bx] - wrong result") ;
    if (get_pf(&ctx) == YES) fail("adc ax, [bx] - PF flag") ;
    if (get_af(&ctx) == YES) fail("adc ax, [bx] - AF flag") ;
    if (get_of(&ctx) == YES) fail("adc ax, [bx] - OF flag") ;
    if (get_sf(&ctx) == YES) fail("adc ax, [bx] - SF flag") ;
    if (get_cf(&ctx) == YES) fail("adc ax, [bx] - CF flag") ;
    if (get_zf(&ctx) == YES) fail("adc ax, [bx] - ZF flag") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    ctx.ax.w = 0x4F3D ;
    set_cf(&ctx, YES) ;
    char opcodes6[] = { 0x15, 0x81, 0xfd } ; // add ax, 0xfd81
    emu_write_bytes(&ctx, opcodes6, 3) ;
    emu_step(&ctx) ;
    if (ctx.ax.w != 0x4CBF) fail("adc ax, 0xfd81 - wrong result") ;
    if (get_cf(&ctx) == NO) fail("adc ax, 0xfd81 - CF flag") ;
    if (get_of(&ctx) == YES) fail("adc ax, 0xfd81 - OF flag") ;
    if (get_zf(&ctx) == YES) fail("adc ax, 0xfd81 - ZF flag") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    ctx.dx.b.l = 0x03 ;
    ctx.bx.b.l =  0x64 ;
    set_cf(&ctx, YES) ;
    char opcodes7[] = { 0x18, 0xd3 } ; // sbb bl, dl
    emu_write_bytes(&ctx, opcodes7, 2) ;
    emu_step(&ctx) ;
    if (ctx.bx.b.l != 0x60) fail("sbb bl, dl - wrong result") ;
    if (get_pf(&ctx) == NO) fail("sbb bl, dl - PF flag") ;
    if (get_af(&ctx) == YES) fail("sbb bl, dl - AF flag") ;
    if (get_of(&ctx) == YES) fail("sbb bl, dl - OF flag") ;
    if (get_sf(&ctx) == YES) fail("sbb bl, dl - SF flag") ;
    if (get_cf(&ctx) != NO) fail("sbb bl, dl - CF flag") ;
    if (get_zf(&ctx) == YES) fail("sbb bl, dl - ZF flag") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    ctx.ax.w = 0x6B3A ;
    set_cf(&ctx, YES) ;
    char opcodes8[] = { 0x1d, 0x2c, 0x4d} ; // sbb ax, 0x4D2C
    emu_write_bytes(&ctx, opcodes8, 3) ;
    emu_step(&ctx) ;
    if (ctx.ax.w != 0x1E0D) fail("sbb ax, 0x4D2C - wrong result") ;
    if (get_pf(&ctx) == YES) fail("sbb ax, 0x4D2C - PF flag") ;
    if (get_af(&ctx) != YES) fail("sbb ax, 0x4D2C - AF flag") ;
    if (get_of(&ctx) == YES) fail("sbb ax, 0x4D2C - OF flag") ;
    if (get_sf(&ctx) == YES) fail("sbb ax, 0x4D2C - SF flag") ;
    if (get_cf(&ctx) == YES) fail("sbb ax, 0x4D2C - CF flag") ;
    if (get_zf(&ctx) == YES) fail("sbb ax, 0x4D2C - ZF flag") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    ctx.dx.b.l = 0x06 ;
    ctx.ds.w = 0xb000 ;
    ctx.bx.w = 0x0010 ;
    ctx.si.w = 0x0006 ;
    char opcodes9[] = {0x22, 0x10} ;
    emu_write_bytes(&ctx, opcodes9, 2) ;
    write_mem_byte(&ctx, 0xB0016, 0xF1) ;
    emu_step(&ctx) ;
    if (ctx.dx.b.l != 0x00) fail("and bl, [bx+si]") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    ctx.ax.b.l = 0xC3 ;
    char opcodes10[] = {0x24, 0x7f} ;
    emu_write_bytes(&ctx, opcodes10, 2) ;
    emu_step(&ctx) ;
    if (ctx.ax.b.l != 0x43) fail("and al, 0x7F - wronng result") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    ctx.bx.b.l = 0x68 ;
    ctx.ax.b.l = 0x28 ;
    char opcodes11[] = {0x00, 0xd8, 0x27} ;
    emu_write_bytes(&ctx, opcodes11, 3) ;
    emu_step(&ctx) ;
    emu_step(&ctx) ;
    if (ctx.ax.b.l != 0x96) fail("daa - wronng result") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    ctx.dx.b.h = 0x41 ;
    ctx.ss.w = 0x0 ;
    ctx.bp.w = 0xE4 ;
    write_mem_byte(&ctx, 0xE8, 0x5A) ;
    char opcodes12[] = {0x2a, 0x76, 0x04} ;
    emu_write_bytes(&ctx, opcodes12, 3) ;
    emu_step(&ctx) ;
    if (ctx.dx.b.h != 0xe7) fail("sub dh, [bp+4] - wronng result") ;
    if (get_pf(&ctx) == NO) fail("sub dh, [bp+4] - PF flag") ;
    if (get_af(&ctx) == NO) fail("sub dh, [bp+4] - AF flag") ;
    if (get_sf(&ctx) != YES) fail("sub dh, [bp+4] - SF flag") ;
    if (get_cf(&ctx) != YES) fail("sub dh, [bp+4] - CF flag") ;
    if (get_zf(&ctx) != NO) fail("sub dh, [bp+4] - ZF flag") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    ctx.ax.b.l = 0x61 ;
    char opcodes13[] = {0x2c, 0x65} ;
    emu_write_bytes(&ctx, opcodes13, 2) ;
    emu_step(&ctx) ;
    if (ctx.ax.b.l != 0xFC) fail("sub al, 0x65 - wronng result") ;
    if (get_cf(&ctx) != YES) fail("sub al, 0x65 - CF flag") ;
    if (get_sf(&ctx) != YES) fail("sub al, 0x65 - SF flag") ;
    if (get_af(&ctx) != YES) fail("sub al, 0x65 - AF flag") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    ctx.ax.b.l = 0x86 ;
    ctx.ax.b.h = 0x07 ;
    char opcodes14[] = {0x28, 0xe0, 0x2f} ;
    emu_write_bytes(&ctx, opcodes14, 3) ;
    emu_step(&ctx) ;
    if (ctx.ax.b.l != 0x7F) fail("sub al, ah - wronng result") ;
    emu_step(&ctx) ;
    if (ctx.ax.b.l != 0x79) fail("das - wronng result") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    ctx.ax.w = 0x07B7 ;
    ctx.ds.w = 0x9080 ;
    ctx.si.w = 0x040E ;
    value.w = 0xA6F0 ;
    write_mem_word(&ctx, 0x90C0E, value) ;
    char opcodes15[] = {0x33, 0x04} ;
    emu_write_bytes(&ctx, opcodes15, 2) ;
    emu_step(&ctx) ;
    if (ctx.ax.w != 0xA147) fail("xor ax, [si] - wrong result") ;
    if (get_sf(&ctx) != YES) fail("xor ax, [si] - SF flag") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    ctx.ax.w = 0xB31C ;
    char opcodes16[] = {0x35, 0x22, 0x55} ;
    emu_write_bytes(&ctx, opcodes16, 3) ;
    emu_step(&ctx) ;
    if (ctx.ax.w != 0xE63E) fail("xor ax, 0x5522 - wrong result") ; 
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    ctx.ax.w = 0x0535 ;
    ctx.bx.b.l = 0x39 ;
    char opcodes17[] = {0x00, 0xd8, 0x37} ;
    emu_write_bytes(&ctx, opcodes17, 3) ;
    emu_step(&ctx) ;
    emu_step(&ctx) ;
    if (ctx.ax.w != 0x0604) fail("aaa - wrong result") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    ctx.dx.b.h = 0x05 ;
    ctx.cx.b.l = 0x06 ;
    char opcodes18[] = {0x38, 0xf1} ;
    emu_write_bytes(&ctx, opcodes18, 2) ;
    emu_step(&ctx) ;
    if (ctx.dx.b.h != 0x05) fail("cmp cl, dh - wrong result") ;
    if (ctx.cx.b.l != 0x06) fail("cmp cl, dh - wrong result") ;
    if (get_pf(&ctx) != NO) fail("cmp cl, dh - PF flag") ;
    if (get_af(&ctx) != NO) fail("cmp cl, dh - AF flag") ;
    if (get_cf(&ctx) != NO) fail("cmp cl, dh - CF flag") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    ctx.ax.b.l = 0x20 ;
    char opcodes19[] = {0x3c, 0x0d} ;
    emu_write_bytes(&ctx, opcodes19, 2) ;
    emu_step(&ctx) ;
    if (ctx.ax.b.l != 0x20) fail("cmp al, 0x0d - wrong result") ;
    if (get_cf(&ctx) != NO) fail("cmp al, 0x0d - CF flag") ;
    if (get_af(&ctx) != YES) fail("cmp al, 0x0d - AF flag") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    ctx.ax.w = 0x0438 ;
    char opcodes20[] = {0x2c, 0x35, 0x3f} ;
    emu_write_bytes(&ctx, opcodes20, 3) ;
    emu_step(&ctx) ;
    emu_step(&ctx) ;
    if (ctx.ax.w != 0x0403) fail("aas - wrong result") ;
    if (get_cf(&ctx) != NO) fail("sub al, 0x35 - CF flag") ;
    if (get_af(&ctx) != NO) fail("sub al, 0x35 - AF flag") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    ctx.ax.w = 0xFFFF ;
    char opcodes21[] = {0x50,0x5b} ;
    emu_write_bytes(&ctx, opcodes21, 2) ;
    emu_step(&ctx) ;
    emu_step(&ctx) ;
    if (ctx.bx.w != 0xFFFF) fail("pop bx - wrong result") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    ctx.ax.w = 0x00FF ;
    ctx.bx.w = 0xFF00 ;
    char opcodes22[] = {0x50,0x53, 0x58, 0x5b} ;
    emu_write_bytes(&ctx, opcodes22, 4) ;
    emu_step(&ctx) ;
    emu_step(&ctx) ;
    emu_step(&ctx) ;
    emu_step(&ctx) ;
    if (ctx.ax.w != 0xFF00) fail("pop ax - wrong result") ;
    if (ctx.bx.w != 0x00FF) fail("pop bx - wrong result") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    char opcodes23[] = {0x70,0xfe} ;
    set_of(&ctx, YES) ;
    emu_write_bytes(&ctx, opcodes23, 2) ;
    emu_step(&ctx) ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    /*
     push ax
     jo label
     pop ax
     pop dx
     pop cx
     label:
     pop bx
    */
    char opcodes24[] = {0x50, 0x70, 0x03, 0x58, 0x5a, 0x59, 0x5b} ;
    set_of(&ctx, YES) ;
    ctx.ax.w = 0xF0F0 ;
    emu_write_bytes(&ctx, opcodes24, 7) ;
    emu_step(&ctx) ;
    emu_step(&ctx) ;
    emu_step(&ctx) ;
    if (ctx.bx.w != 0xF0F0) fail("pop bx - wrong result") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    char opcodes25[] = {0x80, 0xc1, 0xff} ; // add cl, 0xff
    emu_write_bytes(&ctx, opcodes25, 3) ;
    ctx.cx.b.l = 0x01 ;
    emu_step(&ctx) ;
    if (ctx.cx.b.l != 0) fail("add cl, 0xff - wrong result") ;
    if (get_cf(&ctx) != YES) fail("add cl, 0xff - CF flag") ;
    if (get_af(&ctx) != YES) fail("add cl, 0xff - AF flag") ;
    if (get_zf(&ctx) != YES) fail("add cl, 0xff - ZF flag") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    char opcodes26[] = {0x80, 0xc9, 0xff} ;
    emu_write_bytes(&ctx, opcodes26, 3) ;
    ctx.cx.b.l = 0xff ;
    emu_step(&ctx) ;
    if (ctx.cx.b.l != 0xff) fail("or cl, 0xff - wrong result") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    char opcodes27[] = {0x80, 0xd1, 0xff} ; // adc cl, 0xff
    emu_write_bytes(&ctx, opcodes27, 3) ;
    set_cf(&ctx, YES) ;
    ctx.cx.b.l = 0x00 ;
    emu_step(&ctx) ;
    if (ctx.cx.b.l != 0x0) fail("adc cl, 0xff - wrong result") ;
    if (get_cf(&ctx) != YES) fail("adc cl, 0xff - CF flag") ;
    if (get_af(&ctx) != YES) fail("adc cl, 0xff - AF flag") ;
    if (get_of(&ctx) != NO) fail("adc cl, 0xff - OF flag") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    char opcodes28[] = {0x80, 0xd9, 0xff} ; // sbb cl, 0xff
    emu_write_bytes(&ctx, opcodes28, 3) ;
    set_cf(&ctx, YES) ;
    ctx.cx.b.l = 0x00 ;
    emu_step(&ctx) ;
    if (ctx.cx.b.l != 0x0) fail("sbb cl, 0xff - wrong result") ;
    if (get_cf(&ctx) != YES) fail("sbb cl, 0xff - CF flag") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    ctx.cx.w = 0x00 ;
    char opcodes29[] = {0x80, 0xd9, 0xff} ; // sbb cl, 0xff
    emu_write_bytes(&ctx, opcodes29, 3) ;
    emu_step(&ctx) ;
    if (ctx.cx.b.l != 0x01) fail("sbb cl, 0xff - wrong result") ;
    if (get_cf(&ctx) != YES) fail("sbb cl, 0xff - CF flag") ;
    if (get_af(&ctx) != YES) fail("sbb cl, 0xff - AF flag") ;
    emu_cleanup(&ctx) ;
    emu_init(&ctx);
    char opcodes30[] = {0x80, 0xe9, 0xff} ;
    emu_write_bytes(&ctx, opcodes30, 3) ;
    ctx.cx.w = 0x00 ;
    emu_step(&ctx) ;
    if (ctx.cx.b.l != 0x01) fail("sub cl, 0xff - wrong result") ;
    if (get_cf(&ctx) != YES) fail("sub cl, 0xff - CF flag") ;
    if (get_af(&ctx) != YES) fail("sub cl, 0xff - AF flag") ;
    emu_cleanup(&ctx) ;
}
